# Generated by Django 3.2.5 on 2021-07-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='customer_id',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='payment_method_id',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
