# Generated by Django 3.2.5 on 2021-07-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_wallet_payment_method_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer_id',
        ),
    ]
